# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.SmallIntegerField(primary_key=True, serialize=False, verbose_name='\u623f\u95f4id')),
                ('numOfAllPeople', models.SmallIntegerField(verbose_name='\u6751\u843d\u4eba\u6570')),
                ('numOfPlayer', models.SmallIntegerField(verbose_name='\u8fdb\u5165\u623f\u95f4\u7684\u73a9\u5bb6\u4eba\u6570')),
                ('role_queue', models.CharField(max_length=100, verbose_name='\u89d2\u8272\u961f\u5217')),
            ],
            options={
                'verbose_name_plural': '\u6e38\u620f\u623f\u95f4',
            },
        ),
    ]
