# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 22:16
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WerewolfGame', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='config_msg',
            field=models.CharField(default=datetime.datetime(2016, 7, 30, 22, 16, 13, 354429, tzinfo=utc), max_length=100, verbose_name='\u914d\u7f6e\u4fe1\u606f'),
            preserve_default=False,
        ),
    ]
