# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 23:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('WerewolfGame', '0002_room_config_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='god_token',
            field=models.CharField(default=datetime.datetime(2016, 7, 30, 23, 1, 56, 742972, tzinfo=utc), max_length=64, verbose_name='\u6cd5\u5b98\u7684token'),
            preserve_default=False,
        ),
    ]
